@startuml
skinparam backgroundColor #F0F8FF
skinparam defaultFontColor #333333
skinparam arrowColor #666666

' Define borders for all elements
skinparam entity {
  BorderColor #666666
  BackgroundColor #DDDDDD
}

skinparam control {
  BorderColor #666666
  BackgroundColor #DDDDDD
}

skinparam participant {
  BorderColor #666666
  BackgroundColor #DDDDDD
}



start
:Receive TXID, VOUT, Script, Satoshis;
:Compute SHA256 Hash;
note right: UTXO Hash Created
:Store UTXO with Hash Key and Lock Time;

stop

start
:Spend;
:Update UTXO with Spend TXID;
note right: UTXO is marked as spent by the specific TX that used it as an input
stop

right footer Last Modified On: %date("dd-MMM-yyyy")

@enduml
