@startuml
skinparam backgroundColor #F0F8FF
skinparam defaultFontColor #333333
skinparam arrowColor #666666

' Define borders for all elements
skinparam entity {
  BorderColor #666666
  BackgroundColor #DDDDDD
}

skinparam control {
  BorderColor #666666
  BackgroundColor #DDDDDD
}

skinparam participant {
  BorderColor #666666
  BackgroundColor #DDDDDD
}



participant "P2P Service" as P2P
participant "Block Validation Client" as BVC
participant "Block Validation Server" as BVS
participant "Blockchain Client" as BC
queue "blockFoundCh\nBlock Found Channel" as BFC
participant "Background Processor" as BP

P2P -> BVC: BlockFound(ctx, hash, baseUrl)
activate BVC

BVC -> BVS: BlockFound(ctx, req)
activate BVS

BVS -> BC: GetBlockExists(ctx, hash)
activate BC
BC --> BVS: exists / not exists
deactivate BC

alt Block does not exist
    BVS -> BFC: enqueue processBlockFound{hash, baseURL, errCh}

    alt if WaitToComplete is true
        BVS -> BVS: Create errCh
        BVS -> BVS: Wait for errCh
    end
end

BVS --> BVC: Response
deactivate BVS
BVC --> P2P: Response
deactivate BVC

note right of BP
  Background processing of blockFoundCh
end note

BP -> BFC: Dequeue processBlockFound
activate BP
BP -> BP: processBlockFoundChannel(ctx, blockFound)
BP -> BC: GetBlock(ctx, hash)
BP -> BVS: validateBlock(ctx, block, baseUrl)
deactivate BP

left footer Last Modified On: %date("dd-MMM-yyyy")

@enduml
