// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: services/blockchain/blockchain_api/blockchain_api.proto

package blockchain_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BlockchainAPI_Health_FullMethodName            = "/blockchain_api.BlockchainAPI/Health"
	BlockchainAPI_AddBlock_FullMethodName          = "/blockchain_api.BlockchainAPI/AddBlock"
	BlockchainAPI_GetBlock_FullMethodName          = "/blockchain_api.BlockchainAPI/GetBlock"
	BlockchainAPI_GetMedianTime_FullMethodName     = "/blockchain_api.BlockchainAPI/GetMedianTime"
	BlockchainAPI_SubscribeChainTip_FullMethodName = "/blockchain_api.BlockchainAPI/SubscribeChainTip"
)

// BlockchainAPIClient is the client API for BlockchainAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockchainAPIClient interface {
	// Health returns the health of the API.
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	// AddBlock adds a block to the blockchain.  This will be called by BlockValidator.
	AddBlock(ctx context.Context, in *AddBlockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error)
	GetMedianTime(ctx context.Context, in *GetMedianTimeRequest, opts ...grpc.CallOption) (*GetMedianTimeResponse, error)
	SubscribeChainTip(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (BlockchainAPI_SubscribeChainTipClient, error)
}

type blockchainAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockchainAPIClient(cc grpc.ClientConnInterface) BlockchainAPIClient {
	return &blockchainAPIClient{cc}
}

func (c *blockchainAPIClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, BlockchainAPI_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainAPIClient) AddBlock(ctx context.Context, in *AddBlockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BlockchainAPI_AddBlock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainAPIClient) GetBlock(ctx context.Context, in *GetBlockRequest, opts ...grpc.CallOption) (*GetBlockResponse, error) {
	out := new(GetBlockResponse)
	err := c.cc.Invoke(ctx, BlockchainAPI_GetBlock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainAPIClient) GetMedianTime(ctx context.Context, in *GetMedianTimeRequest, opts ...grpc.CallOption) (*GetMedianTimeResponse, error) {
	out := new(GetMedianTimeResponse)
	err := c.cc.Invoke(ctx, BlockchainAPI_GetMedianTime_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainAPIClient) SubscribeChainTip(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (BlockchainAPI_SubscribeChainTipClient, error) {
	stream, err := c.cc.NewStream(ctx, &BlockchainAPI_ServiceDesc.Streams[0], BlockchainAPI_SubscribeChainTip_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &blockchainAPISubscribeChainTipClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlockchainAPI_SubscribeChainTipClient interface {
	Recv() (*ChainTipResponse, error)
	grpc.ClientStream
}

type blockchainAPISubscribeChainTipClient struct {
	grpc.ClientStream
}

func (x *blockchainAPISubscribeChainTipClient) Recv() (*ChainTipResponse, error) {
	m := new(ChainTipResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlockchainAPIServer is the server API for BlockchainAPI service.
// All implementations must embed UnimplementedBlockchainAPIServer
// for forward compatibility
type BlockchainAPIServer interface {
	// Health returns the health of the API.
	Health(context.Context, *emptypb.Empty) (*HealthResponse, error)
	// AddBlock adds a block to the blockchain.  This will be called by BlockValidator.
	AddBlock(context.Context, *AddBlockRequest) (*emptypb.Empty, error)
	GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error)
	GetMedianTime(context.Context, *GetMedianTimeRequest) (*GetMedianTimeResponse, error)
	SubscribeChainTip(*emptypb.Empty, BlockchainAPI_SubscribeChainTipServer) error
	mustEmbedUnimplementedBlockchainAPIServer()
}

// UnimplementedBlockchainAPIServer must be embedded to have forward compatible implementations.
type UnimplementedBlockchainAPIServer struct {
}

func (UnimplementedBlockchainAPIServer) Health(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedBlockchainAPIServer) AddBlock(context.Context, *AddBlockRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBlock not implemented")
}
func (UnimplementedBlockchainAPIServer) GetBlock(context.Context, *GetBlockRequest) (*GetBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (UnimplementedBlockchainAPIServer) GetMedianTime(context.Context, *GetMedianTimeRequest) (*GetMedianTimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedianTime not implemented")
}
func (UnimplementedBlockchainAPIServer) SubscribeChainTip(*emptypb.Empty, BlockchainAPI_SubscribeChainTipServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeChainTip not implemented")
}
func (UnimplementedBlockchainAPIServer) mustEmbedUnimplementedBlockchainAPIServer() {}

// UnsafeBlockchainAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockchainAPIServer will
// result in compilation errors.
type UnsafeBlockchainAPIServer interface {
	mustEmbedUnimplementedBlockchainAPIServer()
}

func RegisterBlockchainAPIServer(s grpc.ServiceRegistrar, srv BlockchainAPIServer) {
	s.RegisterService(&BlockchainAPI_ServiceDesc, srv)
}

func _BlockchainAPI_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainAPIServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainAPI_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainAPIServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainAPI_AddBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainAPIServer).AddBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainAPI_AddBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainAPIServer).AddBlock(ctx, req.(*AddBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainAPI_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainAPIServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainAPI_GetBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainAPIServer).GetBlock(ctx, req.(*GetBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainAPI_GetMedianTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMedianTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainAPIServer).GetMedianTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlockchainAPI_GetMedianTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainAPIServer).GetMedianTime(ctx, req.(*GetMedianTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainAPI_SubscribeChainTip_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlockchainAPIServer).SubscribeChainTip(m, &blockchainAPISubscribeChainTipServer{stream})
}

type BlockchainAPI_SubscribeChainTipServer interface {
	Send(*ChainTipResponse) error
	grpc.ServerStream
}

type blockchainAPISubscribeChainTipServer struct {
	grpc.ServerStream
}

func (x *blockchainAPISubscribeChainTipServer) Send(m *ChainTipResponse) error {
	return x.ServerStream.SendMsg(m)
}

// BlockchainAPI_ServiceDesc is the grpc.ServiceDesc for BlockchainAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockchainAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain_api.BlockchainAPI",
	HandlerType: (*BlockchainAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _BlockchainAPI_Health_Handler,
		},
		{
			MethodName: "AddBlock",
			Handler:    _BlockchainAPI_AddBlock_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _BlockchainAPI_GetBlock_Handler,
		},
		{
			MethodName: "GetMedianTime",
			Handler:    _BlockchainAPI_GetMedianTime_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeChainTip",
			Handler:       _BlockchainAPI_SubscribeChainTip_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/blockchain/blockchain_api/blockchain_api.proto",
}
