@startuml
skinparam backgroundColor #F0F8FF
skinparam defaultFontColor #333333
skinparam arrowColor #666666

' Define borders for all elements
skinparam entity {
  BorderColor #666666
  BackgroundColor #DDDDDD
}

skinparam control {
  BorderColor #666666
  BackgroundColor #DDDDDD
}

skinparam participant {
  BorderColor #666666
  BackgroundColor #DDDDDD
}



participant "Coinbase Server" as Co
participant "Blockchain Store" as St
participant "BlockchainClient" as BC

Co -> Co: catchup(ctx, fromBlock, baseURL)
activate Co

loop while parent block unknown
    Co -> BC: GetBlockHeaders(ctx, fromBlockHeaderHash, 1000)
    BC --> Co: blockHeaders

    loop over blockHeaders
        Co -> St: GetBlockExists(ctx, blockHeader.Hash())
        St --> Co: exists
        alt not exists
            Co -> Co: append to catchupBlockHeaders
        else exists
            Co -> Co: break loop
        end
    end
end

loop reverse over catchupBlockHeaders
    Co -> BC: GetBlock(ctx, blockHeader.Hash())
    BC --> Co: block
    Co -> Co: storeBlock(ctx, block)
    activate Co
    Co -> St: StoreBlock(ctx, block, "")
    St --> Co
    Co -> Co: processCoinbase(ctx, blockId, block.Hash(), block.CoinbaseTx)
    deactivate Co
end

deactivate Co

left footer Last Modified On: %date("dd-MMM-yyyy")

@enduml
