@startuml

participant "UDP6 Client" as Client
participant "UDP6 Listener" as UDPListener

participant "PropagationServer" as PropagationServer

loop for each ipv6Address in ipv6Addresses
    PropagationServer -> UDPListener: Setup UDP Multicast Listener (ipv6Address)
    activate UDPListener
    UDPListener --> PropagationServer: Listener Ready
    deactivate UDPListener
end

loop Listening for UDP Packets
    Client -> UDPListener: Send UDP Packet
    activate UDPListener
    UDPListener -> PropagationServer: Invoke ProcessTransaction

    alt if transaction is valid
        PropagationServer -> TxStore: storeTransaction(ctx, tx)
        activate TxStore
        TxStore --> PropagationServer: Storage confirmation
        deactivate TxStore
        PropagationServer --> PropagationServer: Send success response
    else if transaction is invalid
        PropagationServer --> PropagationServer: Send error response
    end


    PropagationServer -> Validator: Validate(ctx, tx)
    activate Validator
    Validator --> PropagationServer: Validation response
    deactivate Validator

    deactivate UDPListener
end

left footer Last Modified On: 18-Dec-2023

@enduml
