@startuml

participant "Propagation Server" as Server
participant "Configuration System" as Config
participant "UDP6 Listeners" as UDP6
participant "HTTP Server" as HTTP
participant "fRPC Server" as fRPC
participant "QUIC Server" as QUIC
participant "gRPC Server" as gRPC

activate Server

Server -> Config: Get ipv6_addresses
Config --> Server: ipv6Addresses
Server -> UDP6: StartUDP6Listeners(ctx, ipv6Addresses)
activate UDP6
UDP6 --> Server: Listeners started/failed
deactivate UDP6

Server -> Config: Get propagation_httpAddress
Config --> Server: httpAddress
Server -> HTTP: StartHTTPServer(ctx, serverURL)
activate HTTP
HTTP --> Server: HTTP Server started/failed
deactivate HTTP

Server -> Config: Get propagation_frpcListenAddress
Config --> Server: frpcAddress
Server -> fRPC: frpcServer(ctx, frpcAddress)
activate fRPC
fRPC --> Server: fRPC Server started/failed
deactivate fRPC

Server -> Config: Get propagation_quicListenAddress
Config --> Server: quicAddress
Server -> QUIC: quicServer(ctx, quicAddress)
activate QUIC
QUIC --> Server: QUIC Server started/failed
deactivate QUIC

Server -> gRPC: StartGRPCServer(ctx, "propagation")
activate gRPC
gRPC --> Server: gRPC Server started/failed
deactivate gRPC

deactivate Server

left footer Last Modified On: 18-Dec-2023

@enduml
