# docker file used to build the docker image. This was manually pushed to the ecr repo for now and used
# in case you want to make an update to the base image, change this file, build and push.
# you can authenticate to ecr using this:
# $ aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 434394763103.dkr.ecr.eu-north-1.amazonaws.com
FROM ubuntu:noble AS linux-amd64
RUN apt update && apt install -y wget
RUN wget https://github.com/fullstorydev/grpcurl/releases/download/v1.9.2/grpcurl_1.9.2_linux_x86_64.tar.gz && \
    tar -xvf grpcurl_1.9.2_linux_x86_64.tar.gz && \
    mv grpcurl /usr/local/bin && \
    rm grpcurl_1.9.2_linux_x86_64.tar.gz && \
    ln -s /usr/local/bin/grpcurl /usr/bin/grpcurl

FROM ubuntu:noble AS linux-arm64
RUN apt update && apt install -y wget
RUN wget https://github.com/fullstorydev/grpcurl/releases/download/v1.9.2/grpcurl_1.9.2_linux_arm64.tar.gz && \
    tar -xvf grpcurl_1.9.2_linux_arm64.tar.gz && \
    mv grpcurl /usr/local/bin && \
    rm grpcurl_1.9.2_linux_arm64.tar.gz && \
    ln -s /usr/local/bin/grpcurl /usr/bin/grpcurl

ARG TARGETOS
ARG TARGETARCH

FROM ${TARGETOS}-${TARGETARCH}
RUN apt update && \
    apt install -y vim htop curl lsof iputils-ping net-tools dnsutils postgresql-client telnet sysstat procps netcat-openbsd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
