# docker file used to build the docker image.
# The build process is now integrated into CICD
# To use: enable the 'build base container image' Workflow (usually disabled), then push a commit to main/staging branch.
# you can authenticate to ecr using this:
# $ aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 434394763103.dkr.ecr.eu-north-1.amazonaws.com

FROM ubuntu:noble

ARG TARGETOS
ARG TARGETARCH
ARG GITHUB_SHA

# Install packages
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y ca-certificates build-essential gawk bison manpages-dev file curl gnupg wget software-properties-common && \
    add-apt-repository -y ppa:longsleep/golang-backports && \
    apt-get update && \
    apt-get install -y golang-1.24 && \
    ln -s /usr/lib/go-1.24/bin/go /usr/bin/go

# 18 is the latest LTS version of NodeJS
ENV NODE_MAJOR=18

# Add nodesource to apt sources and install nodejs
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list &&\
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN apt-get update && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
