@startuml

participant "Server\n (services/blockvalidation/Server.go)" as Server
participant "Subtree Store" as SubtreeStore

== Subtree Found Handling ==
Server -> Server : SubtreeFound()
activate Server
Server -> SubtreeStore : Exists(spanCtx, subtreeHash[:])
activate SubtreeStore
SubtreeStore --> Server
deactivate SubtreeStore
deactivate Server

== Retrieve Subtree ==
Server -> Server : Get()
activate Server
Server -> SubtreeStore : Get(ctx, request.Hash)
activate SubtreeStore
SubtreeStore --> Server
deactivate SubtreeStore
deactivate Server

left footer Last Modified On: 6-Dec-2023

@enduml
