@startuml
participant "Block Assembly Server" as BlockAssemblyServer
participant "Subtree Store" as SubtreeStore
participant "Tx Store" as TxStore

== Initialize Stores ==
BlockAssemblyServer -> BlockAssemblyServer: NewHTTPBlobServer()
activate BlockAssemblyServer
BlockAssemblyServer -> SubtreeStore: NewStore(logger, subtreeStoreURL, opts...)
activate SubtreeStore
SubtreeStore --> BlockAssemblyServer: subtreeStore
deactivate SubtreeStore
BlockAssemblyServer -> TxStore: NewStore(logger, txStoreURL)
activate TxStore
TxStore --> BlockAssemblyServer: txStore
deactivate TxStore

== Store New Subtree ==
BlockAssemblyServer -> SubtreeStore: Set(ctx, subtreeHash, subtreeBytes, options...)
activate SubtreeStore
SubtreeStore --> BlockAssemblyServer: err
deactivate SubtreeStore

== Store Coinbase Transaction ==
BlockAssemblyServer -> TxStore: Set(ctx, coinbaseTxHash, coinbaseTxBytes)
activate TxStore
TxStore --> BlockAssemblyServer: err
deactivate TxStore

== Remove Subtree TTL ==
BlockAssemblyServer -> SubtreeStore: SetTTL(ctx, subtreeHash, 0, options...)
activate SubtreeStore
SubtreeStore --> BlockAssemblyServer: err
deactivate SubtreeStore

deactivate BlockAssemblyServer

left footer Last Modified On: %date("dd-MMM-yyyy")

@enduml
