@startuml
participant "P2P Service \n(Server.go)" as P2P
control "validatorSubscriptionListener" as Listener
entity "Validator Client \n(Client.go)" as ValidatorClient
entity "Validator Server \n(Server.go)" as ValidatorServer

=== Establish gRPC Stream Subscription ==
P2P -> Listener: Start()
Listener -> ValidatorClient: Subscribe()
ValidatorClient -> ValidatorServer: Subscribe()
ValidatorServer -> Listener: Update subscribers map
Listener -> P2P: Subscription established

=== Send Failed Transaction Notification ==
group Upon failed transaction
    ValidatorServer -> ValidatorServer: sendInvalidTxNotification()
    loop For each subscriber
        ValidatorServer -> P2P: gRPC Send(notification)
    end
end

left footer Last Modified On: 22-December-2023

@enduml
