@startuml
participant "Propagation Module \n(services/propagation/Server.go)" as Propagation
participant "SubtreeValidation Module \n(services/SubtreeValidation/Server.go)" as SubtreeValidation
entity "Validator" as Validator

== Transaction Propagation ==
Propagation -> Propagation: ProcessTransaction()
activate Propagation
Propagation -> Validator: Validate()
activate Validator
Validator -> Propagation: Return errors, if any
deactivate Validator
deactivate Propagation

== Block Validation ==
SubtreeValidation -> SubtreeValidation: blessMissingTransaction()
activate SubtreeValidation
SubtreeValidation -> Validator: Validate()

Validator -> SubtreeValidation: Return errors, if any

deactivate SubtreeValidation

left footer Last Modified On: 27-May-2024

@enduml
