@startuml
participant Propagation as P
participant Validator as V
participant "Subtree Validation" as SV
participant "Block Assembly" as BA
participant P2P

P -> V: New Transaction\n(kafka_validatortxsConfig)
V -> BA: New Transaction\n(kafka_txsConfig)
V -> SV: New UTXO Meta Data\n(kafka_txmetaConfig)
V -> P2P: Rejected Transaction\n(kafka_rejectedTxConfig)
@enduml
