@startuml
participant "Block Assembly" as BlockAssembly
participant "UTXO Store" as UTXOStore

== Create Coinbase TX ==

BlockAssembly -> BlockAssembly: processCoinbaseUtxos(ctx, block)
BlockAssembly -> UTXOStore: Create(ctx, block.CoinbaseTx, blockHeight+100)
activate UTXOStore

UTXOStore --> BlockAssembly: Confirmation
deactivate UTXOStore


== Delete Coinbase TX ==

BlockAssembly -> UTXOStore: Delete(Coinbase UTXO)
activate UTXOStore

UTXOStore --> BlockAssembly: Confirmation
deactivate UTXOStore

left footer Last Modified On: 4-June-2024

@enduml
