@startuml
skinparam backgroundColor #F0F8FF
skinparam defaultFontColor #333333
skinparam arrowColor #666666

' Define borders for all elements
skinparam entity {
  BorderColor #666666
  BackgroundColor #DDDDDD
}

skinparam control {
  BorderColor #666666
  BackgroundColor #DDDDDD
}

skinparam participant {
  BorderColor #666666
  BackgroundColor #DDDDDD
}




participant "Legacy Service" as LegacyService
participant "Blockchain Service" as BlockchainService
participant "FSM" as FSM

== Startup ==
[-> LegacyService : Start
activate LegacyService
LegacyService -> LegacyService : Initialize

== LegacySync Request ==
LegacyService -> BlockchainService : LegacySync (gRPC)
activate BlockchainService

BlockchainService -> FSM : LegacySync Event
activate FSM

FSM -> FSM : Transition to \nLegacySyncing

FSM --> BlockchainService : State Updated
deactivate FSM

BlockchainService --> LegacyService : LegacySync Response
deactivate BlockchainService

LegacyService -> LegacyService : Start Legacy Sync Process

left footer Last Modified On: %date("dd-MMM-yyyy")
@enduml
