package util

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"math"

	"github.com/libsv/go-p2p/chaincfg/chainhash"
	"github.com/libsv/go-p2p/wire"
)

type Subtree struct {
	Height           int
	Fees             uint64
	Nodes            []*chainhash.Hash
	ConflictingNodes []*chainhash.Hash // conflicting nodes need to be checked when doing block assembly

	// temporary (calculated) variables
	rootHash *chainhash.Hash
	treeSize int
}

// NewTree creates a new Subtree with a fixed height
func NewTree(height int) *Subtree {
	var treeSize = int(math.Pow(2, float64(height))) // 1024 * 1024
	return &Subtree{
		Nodes:    make([]*chainhash.Hash, 0, treeSize),
		Height:   height,
		treeSize: treeSize,
	}
}

func NewTreeByLeafCount(maxNumberOfLeaves int) *Subtree {
	if !IsPowerOfTwo(maxNumberOfLeaves) {
		panic("numberOfLeaves must be a power of two")
	}

	height := math.Ceil(math.Log2(float64(maxNumberOfLeaves)))
	return NewTree(int(height))
}

func (st *Subtree) Size() int {
	return cap(st.Nodes)
}

func (st *Subtree) Length() int {
	return len(st.Nodes)
}

func (st *Subtree) IsComplete() bool {
	return len(st.Nodes) == cap(st.Nodes)
}

func (st *Subtree) ReplaceRootNode(node *chainhash.Hash) *chainhash.Hash {
	if len(st.Nodes) < 1 {
		st.Nodes = append(st.Nodes, node)
	} else {
		st.Nodes[0] = node
	}

	st.rootHash = nil // reset rootHash

	return st.RootHash()
}

func (st *Subtree) AddNode(node *chainhash.Hash, fee uint64) error {
	if (len(st.Nodes) + 1) > st.treeSize {
		return fmt.Errorf("subtree is full")
	}

	st.Nodes = append(st.Nodes, node)
	st.rootHash = nil // reset rootHash
	st.Fees += fee

	return nil
}

func (st *Subtree) AddNodes(nodes []*chainhash.Hash) error {
	if (len(st.Nodes) + len(nodes)) > st.treeSize {
		return fmt.Errorf("subtree is full")
	}

	st.Nodes = append(st.Nodes, nodes...)
	st.rootHash = nil // reset rootHash

	return nil
}

func (st *Subtree) RootHash() *chainhash.Hash {
	if st.rootHash != nil {
		return st.rootHash
	}

	// calculate rootHash
	store, err := st.BuildMerkleTreeStoreFromBytes()
	if err != nil {
		return nil
	}

	st.rootHash = store[len(store)-1]

	return st.rootHash
}

func (st *Subtree) Difference(ids txMap) ([]*chainhash.Hash, error) {
	// return all the ids that are in st.Nodes, but not in ids
	diff := make([]*chainhash.Hash, 0, 1_000)
	for _, id := range st.Nodes {
		if !ids.Exists(*id) {
			diff = append(diff, id)
		}
	}

	//fmt.Printf("diff: %d\n", len(diff))
	//for i := 0; i < len(diff); i++ {
	//	hash, _ := chainhash.NewHash(diff[i][:])
	//	fmt.Printf("%s\n", hash.String())
	//	if i > 10 {
	//		break
	//	}
	//}

	return diff, nil
}

func (st *Subtree) BuildMerkleTreeStoreFromBytes() ([]*chainhash.Hash, error) {
	// Calculate how many entries are re?n array of that size.
	nextPoT := NextPowerOfTwo(len(st.Nodes))
	arraySize := nextPoT*2 - 1
	// we do not include the original nodes in the merkle tree
	merkles := make([]*chainhash.Hash, arraySize-len(st.Nodes))

	if arraySize == 1 {
		// Handle this Bitcoin exception that the merkle root is the same as the transaction hash if there
		// is only one transaction.
		return st.Nodes, nil
	}

	// Start the array offset after the last transaction and adjusted to the
	// next power of two.
	offset := nextPoT - len(st.Nodes)
	var hash [32]byte
	var currentMerkle *chainhash.Hash
	var currentMerkle1 *chainhash.Hash
	for i := 0; i < arraySize-1; i += 2 {
		if i < len(st.Nodes) {
			currentMerkle = st.Nodes[i]
			currentMerkle1 = st.Nodes[i+1]
		} else {
			currentMerkle = merkles[i-len(st.Nodes)]
			currentMerkle1 = merkles[i-len(st.Nodes)+1]
		}

		switch {
		// When there is no left child node, the parent is nil ("") too.
		case currentMerkle == nil:
			merkles[offset] = &chainhash.Hash{}

		// When there is no right child, the parent is generated by
		// hashing the concatenation of the left child with itself.
		case currentMerkle1 == nil:
			hash = sha256.Sum256(append(currentMerkle[:], currentMerkle[:]...))
			hash = sha256.Sum256(hash[:])
			merkles[offset], _ = chainhash.NewHash(hash[:])

		// The normal case sets the parent node to the double sha256
		// of the concatenation of the left and right children.
		default:
			hash = sha256.Sum256(append(currentMerkle[:], currentMerkle1[:]...))
			hash = sha256.Sum256(hash[:])
			merkles[offset], _ = chainhash.NewHash(hash[:])
		}
		offset++
	}

	return merkles, nil
}

func (st *Subtree) Serialize() ([]byte, error) {
	buf := bytes.NewBuffer([]byte{})

	// write root hash - this is only for checking the correctness of the data
	_, err := buf.Write(st.RootHash()[:])
	if err != nil {
		return nil, fmt.Errorf("unable to write root hash: %v", err)
	}

	// write fees
	if err = wire.WriteVarInt(buf, 0, st.Fees); err != nil {
		return nil, fmt.Errorf("unable to write fees: %v", err)
	}

	// write number of nodes
	if err = wire.WriteVarInt(buf, 0, uint64(len(st.Nodes))); err != nil {
		return nil, fmt.Errorf("unable to write number of nodes: %v", err)
	}

	// write nodes
	for _, node := range st.Nodes {
		_, err = buf.Write(node[:])
		if err != nil {
			return nil, fmt.Errorf("unable to write node: %v", err)
		}
	}

	// write number of conflicting nodes
	if err = wire.WriteVarInt(buf, 0, uint64(len(st.ConflictingNodes))); err != nil {
		return nil, fmt.Errorf("unable to write number of conflicting nodes: %v", err)
	}

	// write conflicting nodes
	for _, node := range st.ConflictingNodes {
		_, err = buf.Write(node[:])
		if err != nil {
			return nil, fmt.Errorf("unable to write conflicting node: %v", err)
		}
	}

	return buf.Bytes(), nil
}

func (st *Subtree) Deserialize(b []byte) (err error) {
	buf := bytes.NewBuffer(b)

	// read root hash
	var rootHash [32]byte
	_, err = buf.Read(rootHash[:])
	if err != nil {
		return fmt.Errorf("unable to read root hash: %v", err)
	}

	// read fees
	st.Fees, err = wire.ReadVarInt(buf, 0)
	if err != nil {
		return fmt.Errorf("unable to read fees: %v", err)
	}

	// read number of nodes
	numNodes, err := wire.ReadVarInt(buf, 0)
	if err != nil {
		return fmt.Errorf("unable to read number of nodes: %v", err)
	}

	// read nodes
	st.Nodes = make([]*chainhash.Hash, numNodes)
	for i := uint64(0); i < numNodes; i++ {
		st.Nodes[i], err = chainhash.NewHash(buf.Next(32))
		if err != nil {
			return fmt.Errorf("unable to read node: %v", err)
		}
	}

	// read number of conflicting nodes
	numConflictingNodes, err := wire.ReadVarInt(buf, 0)
	if err != nil {
		return fmt.Errorf("unable to read number of conflicting nodes: %v", err)
	}

	// read conflicting nodes
	st.ConflictingNodes = make([]*chainhash.Hash, numConflictingNodes)
	for i := uint64(0); i < numConflictingNodes; i++ {
		st.ConflictingNodes[i], err = chainhash.NewHash(buf.Next(32))
		if err != nil {
			return fmt.Errorf("unable to read conflicting node: %v", err)
		}
	}

	// calculate rootHash and compare with given rootHash
	if !bytes.Equal(st.RootHash()[:], rootHash[:]) {
		return fmt.Errorf("root hash mismatch")
	}

	return nil
}
