@startuml
participant "Blockchain Service" as Blockchain
participant "Kafka" as Kafka
participant "Block Persister Service" as BlockPersister
database "TxMetaStore" as TMS
database "Substree Store" as SubtreeStore
database "Decorated Block Store" as BlockStore


Blockchain -> Kafka: Emit Kafka Block Notification
Kafka -> BlockPersister: Notify Block Received
BlockPersister -> BlockPersister: blockFinalHandler(ctx, _, blockBytes)
activate BlockPersister
BlockPersister -> BlockPersister: Create file for block
BlockPersister -> BlockPersister: Write block header to file
BlockPersister -> BlockPersister: Write number of block transactions to file
BlockPersister -> BlockPersister: Write Coinbase Tx to file
loop for each Subtree in the Block
    BlockPersister -> BlockPersister: processSubtree(ctx, subtreeHash)
    activate BlockPersister
    BlockPersister -> SubtreeStore: Get Subtree from Subtree Store
    loop for each 1000s Tx in Subtree
        BlockPersister -> TMS : MetaBatchDecorate Tx batch
        TMS --> BlockPersister
        BlockPersister -> BlockPersister : Checks if Tx is not Coinbase Tx
        alt if Tx is not Coinbase Tx then
            BlockPersister -> BlockPersister: Write Tx to file
        end
    end
    deactivate BlockPersister
end

BlockPersister -> BlockStore: Persist block file to storage
deactivate BlockPersister

left footer Last Modified On: 15-March-2024

@enduml
