@startuml
participant "Blockchain Service" as Blockchain
participant "Kafka" as Kafka
participant "Block Persister Service" as BlockPersister
database "File Storage" as FileStorage

Blockchain -> Kafka: Emit Kafka Block Notification
Kafka -> BlockPersister: Notify Block Received
BlockPersister -> BlockPersister: blocksFinalHandler(ctx, _, blockBytes)
activate BlockPersister
BlockPersister -> BlockPersister: persistBlock(ctx, hash, blockBytes)
activate BlockPersister
BlockPersister -> BlockPersister: Create UTXODiff for block


BlockPersister -> BlockPersister: Create file for block
BlockPersister -> BlockPersister: Write block header to block file (.block)
BlockPersister -> FileStorage: Persist block file (.block) to storage

loop for each Subtree in the Block
    BlockPersister -> FileStorage: Create subtree file (.subtree)
end

BlockPersister -> FileStorage: Create UTXODiff file  (.utxodiff)

activate BlockPersister
BlockPersister -> FileStorage: Create UTXO Set file (.utxoset)
deactivate BlockPersister


deactivate BlockPersister
deactivate BlockPersister


left footer Last Modified On: 7-June-2024

@enduml
