@startuml

package "TX Meta Store" {
    class "tx-meta" {
        - hash: string
        - fee: decimal
        - size_in_bytes: int
        - parents: list<string>
        - blocks: list<string>
        - lock_time: timestamp
    }
}

package "Services" {

    package "Validator" {
        class "ValidatorService" {
            + Create(transaction: tx-meta) : void (deprecated)
        }
    }

    package "Block Assembler" {
        class "BlockAssemblerService" {
            + UpdateTxMinedStatus(transaction: tx-meta, blockHash: string) : void
        }
    }

    package "Block Validation" {
        class "BlockValidationService" {
            + Create(transaction: tx-meta) : void
            + Get(transactionID: string) : tx-meta
            + UpdateTxMinedStatus(transaction: tx-meta, blockHash: string) : void
        }

        package "Block - in Block Validation" {
            class "BlockValidator" {
                {inactive} - validOrderAndBlessed(block: list<tx-meta>): bool
            }
        }
    }
}

"ValidatorService" -down-> "tx-meta" : Creates
"BlockAssemblerService" -down-> "tx-meta" : UpdatesTxMinedStatus
"BlockValidationService" -down-> "tx-meta" : Creates, Get, UpdatesTxMinedStatus
"BlockValidationService" --> "BlockValidator" : validOrderAndBlessed

@enduml
