// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: services/pruner/pruner_api/pruner_api.proto

package pruner_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrunerAPI_HealthGRPC_FullMethodName = "/pruner.PrunerAPI/HealthGRPC"
)

// PrunerAPIClient is the client API for PrunerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrunerAPIClient interface {
	HealthGRPC(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*HealthResponse, error)
}

type prunerAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPrunerAPIClient(cc grpc.ClientConnInterface) PrunerAPIClient {
	return &prunerAPIClient{cc}
}

func (c *prunerAPIClient) HealthGRPC(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PrunerAPI_HealthGRPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrunerAPIServer is the server API for PrunerAPI service.
// All implementations must embed UnimplementedPrunerAPIServer
// for forward compatibility.
type PrunerAPIServer interface {
	HealthGRPC(context.Context, *EmptyMessage) (*HealthResponse, error)
	mustEmbedUnimplementedPrunerAPIServer()
}

// UnimplementedPrunerAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrunerAPIServer struct{}

func (UnimplementedPrunerAPIServer) HealthGRPC(context.Context, *EmptyMessage) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthGRPC not implemented")
}
func (UnimplementedPrunerAPIServer) mustEmbedUnimplementedPrunerAPIServer() {}
func (UnimplementedPrunerAPIServer) testEmbeddedByValue()                   {}

// UnsafePrunerAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrunerAPIServer will
// result in compilation errors.
type UnsafePrunerAPIServer interface {
	mustEmbedUnimplementedPrunerAPIServer()
}

func RegisterPrunerAPIServer(s grpc.ServiceRegistrar, srv PrunerAPIServer) {
	// If the following call pancis, it indicates UnimplementedPrunerAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrunerAPI_ServiceDesc, srv)
}

func _PrunerAPI_HealthGRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrunerAPIServer).HealthGRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrunerAPI_HealthGRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrunerAPIServer).HealthGRPC(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// PrunerAPI_ServiceDesc is the grpc.ServiceDesc for PrunerAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrunerAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pruner.PrunerAPI",
	HandlerType: (*PrunerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthGRPC",
			Handler:    _PrunerAPI_HealthGRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/pruner/pruner_api/pruner_api.proto",
}
