// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: services/subtreevalidation/subtreevalidation_api/subtreevalidation_api.proto

package subtreevalidation_api

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmptyMessage represents an empty message structure used for health check requests.
type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP(), []int{0}
}

// HealthResponse encapsulates the service health status information.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok indicates if the service is operating normally
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// details provides additional context about the service health status
	Details string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	// timestamp records when the health check was performed
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// CheckSubtreeFromBlockRequest defines the input parameters for subtree validation.
type CheckSubtreeFromBlockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hash represents the merkle root hash of the subtree requiring validation
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// base_url specifies the endpoint for retrieving missing transaction data
	BaseUrl string `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// block_height indicates the blockchain height where the subtree is located
	BlockHeight uint32 `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// block_hash uniquely identifies the block containing the subtree
	BlockHash []byte `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// previous_block_hash identifies the block preceding the current block
	PreviousBlockHash []byte `protobuf:"bytes,5,opt,name=previous_block_hash,json=previousBlockHash,proto3" json:"previous_block_hash,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckSubtreeFromBlockRequest) Reset() {
	*x = CheckSubtreeFromBlockRequest{}
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSubtreeFromBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSubtreeFromBlockRequest) ProtoMessage() {}

func (x *CheckSubtreeFromBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSubtreeFromBlockRequest.ProtoReflect.Descriptor instead.
func (*CheckSubtreeFromBlockRequest) Descriptor() ([]byte, []int) {
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP(), []int{2}
}

func (x *CheckSubtreeFromBlockRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *CheckSubtreeFromBlockRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *CheckSubtreeFromBlockRequest) GetBlockHeight() uint32 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *CheckSubtreeFromBlockRequest) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *CheckSubtreeFromBlockRequest) GetPreviousBlockHash() []byte {
	if x != nil {
		return x.PreviousBlockHash
	}
	return nil
}

// CheckSubtreeFromBlockResponse contains the validation result for a subtree check.
type CheckSubtreeFromBlockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// blessed indicates if the subtree passes all validation criteria
	Blessed       bool `protobuf:"varint,1,opt,name=blessed,proto3" json:"blessed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSubtreeFromBlockResponse) Reset() {
	*x = CheckSubtreeFromBlockResponse{}
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSubtreeFromBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSubtreeFromBlockResponse) ProtoMessage() {}

func (x *CheckSubtreeFromBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSubtreeFromBlockResponse.ProtoReflect.Descriptor instead.
func (*CheckSubtreeFromBlockResponse) Descriptor() ([]byte, []int) {
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP(), []int{3}
}

func (x *CheckSubtreeFromBlockResponse) GetBlessed() bool {
	if x != nil {
		return x.Blessed
	}
	return false
}

var File_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto protoreflect.FileDescriptor

const file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDesc = "" +
	"\n" +
	"Lservices/subtreevalidation/subtreevalidation_api/subtreevalidation_api.proto\x12\x15subtreevalidation_api\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0e\n" +
	"\fEmptyMessage\"t\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetails\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xbf\x01\n" +
	"\x1cCheckSubtreeFromBlockRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12!\n" +
	"\fblock_height\x18\x03 \x01(\rR\vblockHeight\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\fR\tblockHash\x12.\n" +
	"\x13previous_block_hash\x18\x05 \x01(\fR\x11previousBlockHash\"9\n" +
	"\x1dCheckSubtreeFromBlockResponse\x12\x18\n" +
	"\ablessed\x18\x01 \x01(\bR\ablessed2\xf9\x01\n" +
	"\x14SubtreeValidationAPI\x12Z\n" +
	"\n" +
	"HealthGRPC\x12#.subtreevalidation_api.EmptyMessage\x1a%.subtreevalidation_api.HealthResponse\"\x00\x12\x84\x01\n" +
	"\x15CheckSubtreeFromBlock\x123.subtreevalidation_api.CheckSubtreeFromBlockRequest\x1a4.subtreevalidation_api.CheckSubtreeFromBlockResponse\"\x00B\x1aZ\x18./;subtreevalidation_apib\x06proto3"

var (
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescOnce sync.Once
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescData []byte
)

func file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP() []byte {
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescOnce.Do(func() {
		file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDesc), len(file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDesc)))
	})
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescData
}

var file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_goTypes = []any{
	(*EmptyMessage)(nil),                  // 0: subtreevalidation_api.EmptyMessage
	(*HealthResponse)(nil),                // 1: subtreevalidation_api.HealthResponse
	(*CheckSubtreeFromBlockRequest)(nil),  // 2: subtreevalidation_api.CheckSubtreeFromBlockRequest
	(*CheckSubtreeFromBlockResponse)(nil), // 3: subtreevalidation_api.CheckSubtreeFromBlockResponse
	(*timestamppb.Timestamp)(nil),         // 4: google.protobuf.Timestamp
}
var file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_depIdxs = []int32{
	4, // 0: subtreevalidation_api.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: subtreevalidation_api.SubtreeValidationAPI.HealthGRPC:input_type -> subtreevalidation_api.EmptyMessage
	2, // 2: subtreevalidation_api.SubtreeValidationAPI.CheckSubtreeFromBlock:input_type -> subtreevalidation_api.CheckSubtreeFromBlockRequest
	1, // 3: subtreevalidation_api.SubtreeValidationAPI.HealthGRPC:output_type -> subtreevalidation_api.HealthResponse
	3, // 4: subtreevalidation_api.SubtreeValidationAPI.CheckSubtreeFromBlock:output_type -> subtreevalidation_api.CheckSubtreeFromBlockResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_init() }
func file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_init() {
	if File_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDesc), len(file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_goTypes,
		DependencyIndexes: file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_depIdxs,
		MessageInfos:      file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes,
	}.Build()
	File_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto = out.File
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_goTypes = nil
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_depIdxs = nil
}
