// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: services/subtreevalidation/subtreevalidation_api/subtreevalidation_api.proto

package subtreevalidation_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// swagger:model EmptyMessage
type EmptyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP(), []int{0}
}

// swagger:model HealthResponse
type HealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok        bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Details   string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	Timestamp uint32 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// swagger:model CheckSubtreeRequest
type CheckSubtreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash    []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	BaseUrl string `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
}

func (x *CheckSubtreeRequest) Reset() {
	*x = CheckSubtreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSubtreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSubtreeRequest) ProtoMessage() {}

func (x *CheckSubtreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSubtreeRequest.ProtoReflect.Descriptor instead.
func (*CheckSubtreeRequest) Descriptor() ([]byte, []int) {
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP(), []int{2}
}

func (x *CheckSubtreeRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *CheckSubtreeRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

// swagger:model CheckSubtreeResponse
type CheckSubtreeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blessed bool `protobuf:"varint,1,opt,name=blessed,proto3" json:"blessed,omitempty"`
}

func (x *CheckSubtreeResponse) Reset() {
	*x = CheckSubtreeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSubtreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSubtreeResponse) ProtoMessage() {}

func (x *CheckSubtreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSubtreeResponse.ProtoReflect.Descriptor instead.
func (*CheckSubtreeResponse) Descriptor() ([]byte, []int) {
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP(), []int{3}
}

func (x *CheckSubtreeResponse) GetBlessed() bool {
	if x != nil {
		return x.Blessed
	}
	return false
}

var File_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto protoreflect.FileDescriptor

var file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDesc = []byte{
	0x0a, 0x4c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x75, 0x62, 0x74, 0x72,
	0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x75, 0x62,
	0x74, 0x72, 0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61,
	0x70, 0x69, 0x2f, 0x73, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15,
	0x73, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x61, 0x70, 0x69, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x58, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22,
	0x44, 0x0a, 0x13, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x61,
	0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61,
	0x73, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x30, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75,
	0x62, 0x74, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x62, 0x6c, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x62, 0x6c, 0x65, 0x73, 0x73, 0x65, 0x64, 0x32, 0xdd, 0x01, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x74,
	0x72, 0x65, 0x65, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x50, 0x49,
	0x12, 0x5a, 0x0a, 0x0a, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x47, 0x52, 0x50, 0x43, 0x12, 0x23,
	0x2e, 0x73, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x25, 0x2e, 0x73, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x0c,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x12, 0x2a, 0x2e, 0x73,
	0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x62, 0x74, 0x72, 0x65,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x75, 0x62, 0x74, 0x72,
	0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x2e, 0x2f, 0x3b, 0x73, 0x75,
	0x62, 0x74, 0x72, 0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescOnce sync.Once
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescData = file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDesc
)

func file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP() []byte {
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescOnce.Do(func() {
		file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescData)
	})
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescData
}

var file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_goTypes = []interface{}{
	(*EmptyMessage)(nil),         // 0: subtreevalidation_api.EmptyMessage
	(*HealthResponse)(nil),       // 1: subtreevalidation_api.HealthResponse
	(*CheckSubtreeRequest)(nil),  // 2: subtreevalidation_api.CheckSubtreeRequest
	(*CheckSubtreeResponse)(nil), // 3: subtreevalidation_api.CheckSubtreeResponse
}
var file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_depIdxs = []int32{
	0, // 0: subtreevalidation_api.SubtreeValidationAPI.HealthGRPC:input_type -> subtreevalidation_api.EmptyMessage
	2, // 1: subtreevalidation_api.SubtreeValidationAPI.CheckSubtree:input_type -> subtreevalidation_api.CheckSubtreeRequest
	1, // 2: subtreevalidation_api.SubtreeValidationAPI.HealthGRPC:output_type -> subtreevalidation_api.HealthResponse
	3, // 3: subtreevalidation_api.SubtreeValidationAPI.CheckSubtree:output_type -> subtreevalidation_api.CheckSubtreeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_init() }
func file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_init() {
	if File_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckSubtreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckSubtreeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_goTypes,
		DependencyIndexes: file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_depIdxs,
		MessageInfos:      file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes,
	}.Build()
	File_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto = out.File
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDesc = nil
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_goTypes = nil
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_depIdxs = nil
}
