// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: services/bootstrap/bootstrap_api/bootstrap_api.proto

package bootstrap_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BootstrapAPI_HealthGRPC_FullMethodName = "/bootstrap_api.BootstrapAPI/HealthGRPC"
	BootstrapAPI_Connect_FullMethodName    = "/bootstrap_api.BootstrapAPI/Connect"
	BootstrapAPI_GetNodes_FullMethodName   = "/bootstrap_api.BootstrapAPI/GetNodes"
)

// BootstrapAPIClient is the client API for BootstrapAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BootstrapAPIClient interface {
	HealthGRPC(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	Connect(ctx context.Context, in *Info, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error)
	GetNodes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeList, error)
}

type bootstrapAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewBootstrapAPIClient(cc grpc.ClientConnInterface) BootstrapAPIClient {
	return &bootstrapAPIClient{cc}
}

func (c *bootstrapAPIClient) HealthGRPC(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, BootstrapAPI_HealthGRPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bootstrapAPIClient) Connect(ctx context.Context, in *Info, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BootstrapAPI_ServiceDesc.Streams[0], BootstrapAPI_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Info, Notification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BootstrapAPI_ConnectClient = grpc.ServerStreamingClient[Notification]

func (c *bootstrapAPIClient) GetNodes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NodeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeList)
	err := c.cc.Invoke(ctx, BootstrapAPI_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BootstrapAPIServer is the server API for BootstrapAPI service.
// All implementations must embed UnimplementedBootstrapAPIServer
// for forward compatibility.
type BootstrapAPIServer interface {
	HealthGRPC(context.Context, *emptypb.Empty) (*HealthResponse, error)
	Connect(*Info, grpc.ServerStreamingServer[Notification]) error
	GetNodes(context.Context, *emptypb.Empty) (*NodeList, error)
	mustEmbedUnimplementedBootstrapAPIServer()
}

// UnimplementedBootstrapAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBootstrapAPIServer struct{}

func (UnimplementedBootstrapAPIServer) HealthGRPC(context.Context, *emptypb.Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthGRPC not implemented")
}
func (UnimplementedBootstrapAPIServer) Connect(*Info, grpc.ServerStreamingServer[Notification]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedBootstrapAPIServer) GetNodes(context.Context, *emptypb.Empty) (*NodeList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedBootstrapAPIServer) mustEmbedUnimplementedBootstrapAPIServer() {}
func (UnimplementedBootstrapAPIServer) testEmbeddedByValue()                      {}

// UnsafeBootstrapAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BootstrapAPIServer will
// result in compilation errors.
type UnsafeBootstrapAPIServer interface {
	mustEmbedUnimplementedBootstrapAPIServer()
}

func RegisterBootstrapAPIServer(s grpc.ServiceRegistrar, srv BootstrapAPIServer) {
	// If the following call pancis, it indicates UnimplementedBootstrapAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BootstrapAPI_ServiceDesc, srv)
}

func _BootstrapAPI_HealthGRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootstrapAPIServer).HealthGRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BootstrapAPI_HealthGRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootstrapAPIServer).HealthGRPC(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BootstrapAPI_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Info)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BootstrapAPIServer).Connect(m, &grpc.GenericServerStream[Info, Notification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BootstrapAPI_ConnectServer = grpc.ServerStreamingServer[Notification]

func _BootstrapAPI_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BootstrapAPIServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BootstrapAPI_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BootstrapAPIServer).GetNodes(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BootstrapAPI_ServiceDesc is the grpc.ServiceDesc for BootstrapAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BootstrapAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bootstrap_api.BootstrapAPI",
	HandlerType: (*BootstrapAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthGRPC",
			Handler:    _BootstrapAPI_HealthGRPC_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _BootstrapAPI_GetNodes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _BootstrapAPI_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/bootstrap/bootstrap_api/bootstrap_api.proto",
}
