CREATE ROLE teranode LOGIN
  PASSWORD 'teranode'
  SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant teranode to postgres;
CREATE
DATABASE teranode
  WITH OWNER = teranode
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;
