@startuml
skinparam backgroundColor #F0F8FF
skinparam defaultFontColor #333333
skinparam arrowColor #666666

' Define borders for all elements
skinparam entity {
  BorderColor #666666
  BackgroundColor #DDDDDD
}

skinparam control {
  BorderColor #666666
  BackgroundColor #DDDDDD
}

skinparam participant {
  BorderColor #666666
  BackgroundColor #DDDDDD
}



title UTXO Persister - Service Initialization and Starting

participant "UTXO Persister Server" as Server
participant "Block Store" as BlockStore
participant "Blockchain Client" as BlockchainClient
participant "Blockchain Store" as BlockchainStore

Server -> Server : New()
activate Server

Server -> BlockStore : Initialize
alt indirect mode
    Server -> BlockchainClient : Initialize
else direct mode
    Server -> BlockchainStore : Initialize
end

Server -> Server : Init()
Server -> Server : readLastHeight()

deactivate Server

Server -> Server : Start()
activate Server

alt fsm_state_restore is true
    Server -> BlockchainClient : Restore()
    Server -> BlockchainClient : WaitForFSMtoTransitionToGivenState()
end

alt BlockchainClient is not nil
    Server -> BlockchainClient : Subscribe()
end

Server -> Server : trigger("startup")
Server --> Server : Enter processing loop

deactivate Server

left footer Last Modified On: %date("dd-MMM-yyyy")

@enduml
