@startuml
participant "TX Validator" as TXValidator
participant "Block Assembly Client" as BA
participant "Block Assembly Server" as Server
participant "Subtree Processor" as SubtreeProcessor

TXValidator -> BA : NewClient(ctx, logger)

TXValidator -> BA : Store(ctx, bData.TxIDChainHash, bData.Fee, bData.Size, bData.LockTime, bData.UtxoHashes)

alt if "batch mode" enabled
    BA -> BA : Add to batch
    BA -> Server : AddTxBatch(ctx, nodeBatch)
    loop for each node in nodeBatch
        Server -> SubtreeProcessor : AddTx(subtreeNode)
        SubtreeProcessor --> SubtreeProcessor : Add(node)
    end
else if "batch mode" disabled
    TXValidator -> BA : Store(ctx, bData.TxIDChainHash, bData.Fee, bData.Size, bData.LockTime, bData.UtxoHashes)
    BA --> Server : AddTx(subtreeNode)
    Server --> SubtreeProcessor : AddTx(subtreeNode)
    SubtreeProcessor --> SubtreeProcessor : Add(node)
end

left footer Last Modified On: 10-Jan-2024

@enduml
