@startuml
participant "Block Assembly" as Client
participant "Blockchain Service" as Blockchain
database "Store" as Store

Client -> Client: submitMiningSolution(ctx, submitMiningSolutionRequest)

alt Failed to submit mining solution
    Client -> Blockchain: InvalidateBlock(request)
    activate Blockchain
    Blockchain -> Store: InvalidateBlock(blockHash)
    activate Store
    Store --> Blockchain: Result
    deactivate Store
    Blockchain --> Client: Response (Empty or Error)
    deactivate Blockchain
end

left footer Last Modified On: 24-Jan-2024

@enduml
