@startuml
participant "Client" as Client
participant "Blockchain Service" as Service
database "Store" as Store

Client -> Service: GetBestBlockHeader(ctx, empty)
activate Service

Service -> Store: GetBestBlockHeader(ctx)
activate Store
Store --> Service: chainTip, meta, err
deactivate Store

alt If Error
    Service --> Client: Return Error
else If Successful
    Service --> Client: GetBlockHeaderResponse
end

deactivate Service

left footer Last Modified On: %date("dd-MMM-yyyy")

@enduml
