
@startuml
participant "Client" as Client
participant "Blockchain Service" as Service
database "Block Store" as Store

Client -> Service: GetLastNBlocks(ctx, request)
activate Service

Service -> Store: GetLastNBlocks(ctx, numberOfBlocks, includeOrphans, fromHeight)
activate Store
Store --> Service: blockInfo / Error
deactivate Store

alt If Error in GetLastNBlocks
    Service --> Client: Return Error
    deactivate Service
else If Successful
    Service --> Client: Create & Return GetLastNBlocksResponse
end

deactivate Service

left footer Last Modified On: 24-Jan-2024

@enduml
