@startuml
actor User as "User"
participant "UI Dashboard" as UIDashboard
participant "AssetService" as AssetService
participant "TxMetaStore" as TxMetaStore

== Fetch Transaction Meta Data ==
User -> UIDashboard: Request Transaction Meta
UIDashboard -> AssetService: /txmeta/:hash/json
AssetService -> AssetService: GetTransactionMeta()
AssetService -> TxMetaStore: Get(context, hash)
TxMetaStore -> AssetService: Return Transaction Meta
AssetService -> UIDashboard: Return Transaction Meta
UIDashboard -> User: Display Transaction Meta

== Fetch Transaction ==
User -> UIDashboard: Request Transaction Details
UIDashboard -> AssetService: /tx/:hash/json
AssetService -> AssetService: GetTransaction()
AssetService -> TxMetaStore: Get(ctx, hash)
TxMetaStore -> AssetService: Return Transaction Details
AssetService -> UIDashboard: Return Transaction Details
UIDashboard -> User: Display Transaction Details

== Fetch Transactions (Stream) ==
User -> UIDashboard: Request Transactions List
UIDashboard -> AssetService: /txs
AssetService -> AssetService: GetTransactions()
AssetService -> TxMetaStore: Get(ctx, hash)
TxMetaStore -> AssetService: Return Transactions List
AssetService -> UIDashboard: Return Transactions List
UIDashboard -> User: Display Transactions List

left footer Last Modified On: 28-Nov-2023

@enduml
