@startuml
participant "Block Validation (Server.go)" as Server
participant "BlockValidation.go" as BlockValidation
participant "UpdateTxMinedStatus\n(model/update-tx-mined.go)" as UpdateTxMinedStatus
participant "TxMetaStore" as TxMetaStore

Server -> Server: catchup() or processBlockFound()

Server -> BlockValidation: ValidateBlock(ctx, block, baseUrl)
activate BlockValidation

BlockValidation -> BlockValidation: finalizeBlockValidation(ctx, block)

BlockValidation -> UpdateTxMinedStatus: UpdateTxMinedStatus
activate UpdateTxMinedStatus

UpdateTxMinedStatus -> TxMetaStore: setMinedMulti(ctx, hashes, blockHash)
activate TxMetaStore

TxMetaStore --> UpdateTxMinedStatus: Mined Status Updated
deactivate TxMetaStore

UpdateTxMinedStatus --> BlockValidation: Return
deactivate UpdateTxMinedStatus

BlockValidation --> BlockValidation: Block Validation Finalized

BlockValidation --> Server: Block Validated
deactivate BlockValidation

left footer Last Modified On: 28-Nov-2023

@enduml
