@startuml
participant "Validator" as ValidateSubtree
entity "Subtree Data" as SubtreeData
participant "Util HTTP Request" as Util
database "Subtree Store" as SubtreeStore
database "Tx Meta Cache" as TxMetaStore


ValidateSubtree -> ValidateSubtree: validateSubtree(ctx, subtreeHash, baseURL)
activate ValidateSubtree

ValidateSubtree -> SubtreeStore: subtreeStore.Exists(spanCtx, subtreeHash[:])
activate SubtreeStore
SubtreeStore --> ValidateSubtree: subtreeExists / err
deactivate SubtreeStore

alt subtreeExists is false
    ValidateSubtree -> Util: DoHTTPRequest(spanCtx, url)
    activate Util
    Util --> ValidateSubtree: subtreeBytes / err
    deactivate Util

    ValidateSubtree -> ValidateSubtree: Process subtreeBytes
    activate TxMetaStore
    loop for each txHash
       ValidateSubtree -> TxMetaStore: GetMeta(gCtx, &txHash)
        TxMetaStore --> ValidateSubtree: txMeta / err
    end
    deactivate TxMetaStore

    ValidateSubtree -> ValidateSubtree: processMissingTransactions(ctx, subtreeHash, missingTxHashesCompacted, baseUrl, txMetaSlice)

    ValidateSubtree -> SubtreeData: Add transactions to Subtree


    ValidateSubtree -> SubtreeData: AddNode(txHash, txMeta.Fee, txMeta.SizeInBytes)

    ValidateSubtree -> SubtreeStore: Set(spanCtx, merkleRoot[:], completeSubtreeBytes)
    activate SubtreeStore
    SubtreeStore --> ValidateSubtree
    deactivate SubtreeStore
end

deactivate ValidateSubtree

deactivate ValidateSubtree

left footer Last Modified On: 28-Jan-2024

@enduml
