// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: services/propagation/propagation_api/propagation_api.proto

package propagation_api

import (
	errors "github.com/bitcoin-sv/teranode/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmptyMessage represents an empty request or response.
// Used when no additional data needs to be transmitted.
// swagger:model EmptyMessage
type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_services_propagation_propagation_api_propagation_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_services_propagation_propagation_api_propagation_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_services_propagation_propagation_api_propagation_api_proto_rawDescGZIP(), []int{0}
}

// HealthResponse provides information about the service's health status.
// swagger:model HealthResponse
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok indicates whether the service is healthy
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// details provides additional information about the health status
	Details string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	// timestamp indicates when the health check was performed
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_services_propagation_propagation_api_propagation_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_propagation_propagation_api_propagation_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_services_propagation_propagation_api_propagation_api_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// GetRequest represents a request to retrieve a transaction by its ID.
// swagger:model GetRequest
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// txid is the transaction ID in bytes
	Txid          []byte `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_services_propagation_propagation_api_propagation_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_propagation_propagation_api_propagation_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_services_propagation_propagation_api_propagation_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

// GetResponse contains the retrieved transaction data.
// swagger:model GetResponse
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tx contains the raw transaction bytes
	Tx            []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_services_propagation_propagation_api_propagation_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_propagation_propagation_api_propagation_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_services_propagation_propagation_api_propagation_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

// ProcessTransactionRequest represents a request to process a single transaction.
// swagger:model ProcessTransactionRequest
type ProcessTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tx contains the raw transaction bytes to process
	Tx            []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessTransactionRequest) Reset() {
	*x = ProcessTransactionRequest{}
	mi := &file_services_propagation_propagation_api_propagation_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTransactionRequest) ProtoMessage() {}

func (x *ProcessTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_propagation_propagation_api_propagation_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTransactionRequest.ProtoReflect.Descriptor instead.
func (*ProcessTransactionRequest) Descriptor() ([]byte, []int) {
	return file_services_propagation_propagation_api_propagation_api_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessTransactionRequest) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

// ProcessTransactionBatchRequest represents a request to process multiple transactions.
// swagger:model ProcessTransactionRequest
type ProcessTransactionBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tx contains an array of raw transaction bytes to process
	Tx            [][]byte `protobuf:"bytes,1,rep,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessTransactionBatchRequest) Reset() {
	*x = ProcessTransactionBatchRequest{}
	mi := &file_services_propagation_propagation_api_propagation_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessTransactionBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTransactionBatchRequest) ProtoMessage() {}

func (x *ProcessTransactionBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_propagation_propagation_api_propagation_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTransactionBatchRequest.ProtoReflect.Descriptor instead.
func (*ProcessTransactionBatchRequest) Descriptor() ([]byte, []int) {
	return file_services_propagation_propagation_api_propagation_api_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessTransactionBatchRequest) GetTx() [][]byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

// ProcessTransactionBatchResponse contains the results of batch transaction processing.
// swagger:model ProcessTransactionBatchResponse
type ProcessTransactionBatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// error contains error messages for each transaction in the batch
	// empty string indicates success for that transaction
	Errors        []*errors.TError `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessTransactionBatchResponse) Reset() {
	*x = ProcessTransactionBatchResponse{}
	mi := &file_services_propagation_propagation_api_propagation_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessTransactionBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTransactionBatchResponse) ProtoMessage() {}

func (x *ProcessTransactionBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_propagation_propagation_api_propagation_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTransactionBatchResponse.ProtoReflect.Descriptor instead.
func (*ProcessTransactionBatchResponse) Descriptor() ([]byte, []int) {
	return file_services_propagation_propagation_api_propagation_api_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessTransactionBatchResponse) GetErrors() []*errors.TError {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_services_propagation_propagation_api_propagation_api_proto protoreflect.FileDescriptor

var file_services_propagation_propagation_api_propagation_api_proto_rawDesc = string([]byte{
	0x0a, 0x3a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x61,
	0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x72,
	0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x74, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x20, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x22, 0x1d, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x22, 0x2b, 0x0a, 0x19, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x22, 0x30, 0x0a, 0x1e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x22, 0x49, 0x0a, 0x1f, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x2e, 0x54, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x32, 0xc3, 0x02, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x50, 0x49, 0x12, 0x4e, 0x0a, 0x0a, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x47, 0x52, 0x50, 0x43, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x2e, 0x70,
	0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x70, 0x61,
	0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x7e, 0x0a, 0x17, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x2f, 0x2e, 0x70, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x3b,
	0x70, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_services_propagation_propagation_api_propagation_api_proto_rawDescOnce sync.Once
	file_services_propagation_propagation_api_propagation_api_proto_rawDescData []byte
)

func file_services_propagation_propagation_api_propagation_api_proto_rawDescGZIP() []byte {
	file_services_propagation_propagation_api_propagation_api_proto_rawDescOnce.Do(func() {
		file_services_propagation_propagation_api_propagation_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_propagation_propagation_api_propagation_api_proto_rawDesc), len(file_services_propagation_propagation_api_propagation_api_proto_rawDesc)))
	})
	return file_services_propagation_propagation_api_propagation_api_proto_rawDescData
}

var file_services_propagation_propagation_api_propagation_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_services_propagation_propagation_api_propagation_api_proto_goTypes = []any{
	(*EmptyMessage)(nil),                    // 0: propagation_api.EmptyMessage
	(*HealthResponse)(nil),                  // 1: propagation_api.HealthResponse
	(*GetRequest)(nil),                      // 2: propagation_api.GetRequest
	(*GetResponse)(nil),                     // 3: propagation_api.GetResponse
	(*ProcessTransactionRequest)(nil),       // 4: propagation_api.ProcessTransactionRequest
	(*ProcessTransactionBatchRequest)(nil),  // 5: propagation_api.ProcessTransactionBatchRequest
	(*ProcessTransactionBatchResponse)(nil), // 6: propagation_api.ProcessTransactionBatchResponse
	(*timestamppb.Timestamp)(nil),           // 7: google.protobuf.Timestamp
	(*errors.TError)(nil),                   // 8: errors.TError
}
var file_services_propagation_propagation_api_propagation_api_proto_depIdxs = []int32{
	7, // 0: propagation_api.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	8, // 1: propagation_api.ProcessTransactionBatchResponse.errors:type_name -> errors.TError
	0, // 2: propagation_api.PropagationAPI.HealthGRPC:input_type -> propagation_api.EmptyMessage
	4, // 3: propagation_api.PropagationAPI.ProcessTransaction:input_type -> propagation_api.ProcessTransactionRequest
	5, // 4: propagation_api.PropagationAPI.ProcessTransactionBatch:input_type -> propagation_api.ProcessTransactionBatchRequest
	1, // 5: propagation_api.PropagationAPI.HealthGRPC:output_type -> propagation_api.HealthResponse
	0, // 6: propagation_api.PropagationAPI.ProcessTransaction:output_type -> propagation_api.EmptyMessage
	6, // 7: propagation_api.PropagationAPI.ProcessTransactionBatch:output_type -> propagation_api.ProcessTransactionBatchResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_propagation_propagation_api_propagation_api_proto_init() }
func file_services_propagation_propagation_api_propagation_api_proto_init() {
	if File_services_propagation_propagation_api_propagation_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_propagation_propagation_api_propagation_api_proto_rawDesc), len(file_services_propagation_propagation_api_propagation_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_propagation_propagation_api_propagation_api_proto_goTypes,
		DependencyIndexes: file_services_propagation_propagation_api_propagation_api_proto_depIdxs,
		MessageInfos:      file_services_propagation_propagation_api_propagation_api_proto_msgTypes,
	}.Build()
	File_services_propagation_propagation_api_propagation_api_proto = out.File
	file_services_propagation_propagation_api_propagation_api_proto_goTypes = nil
	file_services_propagation_propagation_api_propagation_api_proto_depIdxs = nil
}
