@startuml ChainIntegrity Initialization

participant "Main Application" as Main
entity "Configuration Loader" as ConfigLoader
database "Blockchain Store" as BlockchainDB
database "Subtree Store" as SubtreeStore
database "Transaction Store" as TxStore
database "UTXO Store" as UTXOStore

Main -> ConfigLoader: GetURL("blockchain_store")
ConfigLoader --> Main: Return blockchainStoreURL
Main -> BlockchainDB: Initialize with blockchainStoreURL
BlockchainDB --> Main: Initialized

Main -> ConfigLoader: GetURL("subtreestore")
ConfigLoader --> Main: Return subtreeStoreUrl
Main -> SubtreeStore: Initialize with subtreeStoreUrl
SubtreeStore --> Main: Initialized

Main -> ConfigLoader: GetURL("txstore")
ConfigLoader --> Main: Return txStoreUrl
Main -> TxStore: Initialize with txStoreUrl
TxStore --> Main: Initialized

Main -> ConfigLoader: GetURL("utxostore")
ConfigLoader --> Main: Return utxoStoreURL
Main -> UTXOStore: Initialize with utxoStoreURL
UTXOStore --> Main: Initialized

left footer " Last Modified On: 18-June-2024. © 2024 Bitcoin SV. All rights reserved."

@enduml
