@startuml
participant "Block Assembly Server\n(services/blockassembly/Server.go)" as BlockAssemblyServer
participant "Remote TTL\n(services/blockassembly/remotettl.go)" as RemoteTTL
participant "Asset Client\n(asset/Client.go)" as AssetClient
participant "Asset Server\n(asset/Server.go)" as AssetServer
database "Blob Subtree Store" as BlobStore

== New Subtree Scenario ==
BlockAssemblyServer -> RemoteTTL : Set(ctx, subtree)
activate RemoteTTL
RemoteTTL -> AssetClient : set(ctx, subtree)
activate AssetClient
AssetClient -> AssetServer : Set(ctx, subtree)
activate AssetServer
AssetServer -> BlobStore : Set(ctx, subtree)
activate BlobStore
BlobStore --> AssetServer
deactivate BlobStore
AssetServer --> AssetClient
deactivate AssetServer
AssetClient --> RemoteTTL
deactivate AssetClient
RemoteTTL --> BlockAssemblyServer
deactivate RemoteTTL

== Clear Subtree TTL Scenario ==
BlockAssemblyServer -> BlockAssemblyServer : submitMiningSolution(ctx, block)
activate BlockAssemblyServer
BlockAssemblyServer -> BlockAssemblyServer : removeSubtreesTTL(ctx, Block)
loop For Each Subtree in the Block
    BlockAssemblyServer -> RemoteTTL : SetTTL(ctx, ttl)
    activate RemoteTTL
    RemoteTTL -> AssetClient : SetTTL(ctx, ttl)
    activate AssetClient
    AssetClient -> AssetServer : SetTTL(ctx, ttl)
    activate AssetServer
    AssetServer -> BlobStore : SetTTL(ctx, ttl)
    activate BlobStore
    BlobStore --> AssetServer
    deactivate BlobStore
    AssetServer --> AssetClient
    deactivate AssetServer
    AssetClient --> RemoteTTL
    deactivate AssetClient
    RemoteTTL --> BlockAssemblyServer
    deactivate RemoteTTL
end
deactivate BlockAssemblyServer

left footer Last Modified On: 4-Dec-2023

@enduml
