@startuml overview
actor TxBlaster
actor Propagation
database txStore
actor Validator
database txMetaStore
actor BlockAssembler
participant SubtreeProcessor
database utxoStore
database subtreeStore
Actor Blockchain
database blockchainStore
actor Miner

TxBlaster -[#blue]> Propagation : grpc:ProcessTransaction(tx)
Propagation -[#red]-> txStore: storeTransaction
Propagation -[#blue]> Validator: grpc:ValidateTransaction(tx)

Validator -[#red]-> txMetaStore: Create(txMeta)
Validator -[#blue]> BlockAssembler: grpc:AddTx(tx)

BlockAssembler -[#red]> txMetaStore: Get(txMeta)
BlockAssembler -> SubtreeProcessor: Add(tx)
SubtreeProcessor -[#red]> utxoStore: Store(tx)
SubtreeProcessor -> SubtreeProcessor : addNode
SubtreeProcessor -> SubtreeProcessor : newSubtreeChan
SubtreeProcessor -[#red]-> subtreeStore : Set



Miner -[#blue]> BlockAssembler : grpc:getMiningCandidate()
Miner -> Miner : randomDelay()
Miner -[#blue]> BlockAssembler : grpc:SubmitMiningSolution(solution))

BlockAssembler -[#blue]> Blockchain : grpc:AddBlock(block)
BlockAssembler -[#red]-> txStore : Set(coinbase tx)
BlockAssembler -[#red]-> subtreeStore : SetTTL(hash)
Blockchain -[#red]-> blockchainStore : StoreBlock(block)
Blockchain -[#blue]> BlockAssembler : grpc:SendNotification(block)
BlockAssembler -[#blue]> Blockchain : grpc:GetBestBlockHeader()
BlockAssembler -> BlockAssembler : (if-new-block)
BlockAssembler -[#blue]> Blockchain : grpc:GetBlock(hash)
BlockAssembler -[#blue]> SubtreeProcessor : grpc:MoveUpBlock(block)
BlockAssembler -[#blue]> Blockchain : grpc:SetState(block)
Blockchain -[#red]-> blockchainStore : SetState(block)


@enduml
