@startuml overview
Propagation --> txStore: grpc:Set(tx)
Propagation -> Validator: grpc:ValidateTransaction(tx)

Validator --> txMetaStore: grpc:Create(txMeta)
Validator -> BlockAssembler: grpc:AddTx(tx)

BlockAssembler --> txMetaStore: grpc:Get(txMeta)
BlockAssembler --> SubtreeProcessor: Add(tx)
SubtreeProcessor --> utxoStore: Store(tx)

Miner -> BlockAssembler : grpc:getMiningCandidate()
Miner -> Miner : randomDelay()
Miner -> BlockAssembler : grpc:SubmitMiningSolution(solution))

BlockAssembler -> Blockchain : grpc:AddBlock(block)
BlockAssembler -> txStore : grpc:Set(tx)
BlockAssembler --> subtreeStore : SetTTL(hash)
Blockchain --> BlockchainStore : StoreBlock(block)
Blockchain -> BlockAssembler : grpc:SendNotification(block)
BlockAssembler -> Blockchain : grpc:GetBestBlockHeader()
BlockAssembler -> BlockAssembler : (if-new-block)
BlockAssembler -> Blockchain : grpc:GetBlock(hash)
BlockAssembler -> SubtreeProcessor : grpc:MoveUpBlock(block)
BlockAssembler -> Blockchain : grpc:SetState(block)
Blockchain --> BlockchainStore : SetState(block)

@enduml
