@startuml overview
actor TxBlaster
actor Propagation
database txstore
actor Validator
actor txMetaStore
database txmetastore
actor BlockAssembler
participant SubtreeProcessor
actor utxoStore
database utxostore
database subtreestore
Actor Blockchain
database blockchainstore
actor Miner

TxBlaster -[#blue]> Propagation : grpc:Set(tx)
Propagation -[#red]-> txstore: storeTransaction
Propagation -[#blue]> Validator: grpc:ValidateTransaction(tx)

Validator -[#blue]-> txMetaStore: grpc:Create(txMeta)
txMetaStore -[#red]-> txmetastore: Create
Validator -[#blue]> BlockAssembler: grpc:AddTx(tx)

BlockAssembler -[#blue]> txMetaStore: grpc:Get(txMeta)
BlockAssembler -> SubtreeProcessor: Add(tx)
SubtreeProcessor -[#blue]> utxoStore: grpc:Store(tx)
utxoStore -[#red]-> utxostore: Store
SubtreeProcessor -> SubtreeProcessor : addNode
SubtreeProcessor -> SubtreeProcessor : newSubtreeChan
SubtreeProcessor -[#red]-> subtreestore : Set



Miner -[#blue]> BlockAssembler : grpc:getMiningCandidate()
Miner -> Miner : randomDelay()
Miner -[#blue]> BlockAssembler : grpc:SubmitMiningSolution(solution))

BlockAssembler -[#blue]> Blockchain : grpc:AddBlock(block)
BlockAssembler -[#red]-> txstore : Set(coinbase tx)
BlockAssembler -[#red]-> subtreestore : SetTTL(hash)
Blockchain -[#red]-> blockchainstore : StoreBlock(block)
Blockchain -[#blue]> BlockAssembler : grpc:SendNotification(block)
BlockAssembler -[#blue]> Blockchain : grpc:GetBestBlockHeader()
BlockAssembler -> BlockAssembler : (if-new-block)
BlockAssembler -[#blue]> Blockchain : grpc:GetBlock(hash)
BlockAssembler -[#blue]> SubtreeProcessor : grpc:MoveUpBlock(block)
BlockAssembler -[#blue]> Blockchain : grpc:SetState(block)
Blockchain -[#red]-> blockchainstore : SetState(block)


@enduml
