@startuml TXFlow
skinparam backgroundColor #F0F8FF
skinparam defaultFontColor #333333
skinparam arrowColor #666666

' Define borders for all elements
skinparam entity {
  BorderColor #666666
  BackgroundColor #DDDDDD
}

skinparam control {
  BorderColor #666666
  BackgroundColor #DDDDDD
}

skinparam participant {
  BorderColor #666666
  BackgroundColor #DDDDDD
}



hide footbox
skinparam ParticipantPadding 15
skinparam BoxPadding 10

actor Client
participant "Stateless Proxy" as Proxy
database "Shard" as Shard
participant "Storage Server" as Storage

Client -> Proxy : Write Request (Key/Value)
Proxy -> Shard : Key Lookup
Shard -> Storage : Write (Key/Value)
Storage -> Shard : Acknowledge Write
Shard -> Proxy : Acknowledge Write
Proxy -> Client : Acknowledge Write

@enduml
