CREATE ROLE miner1 LOGIN
  PASSWORD 'miner1'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant miner1 to postgres;
CREATE
DATABASE ubsv1
  WITH OWNER = miner1
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE miner2 LOGIN
  PASSWORD 'miner2'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant miner2 to postgres;
CREATE
DATABASE ubsv2
  WITH OWNER = miner2
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE miner3 LOGIN
  PASSWORD 'miner3'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant miner3 to postgres;
CREATE
DATABASE ubsv3
  WITH OWNER = miner3
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE m1 LOGIN
  PASSWORD 'm1'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant m1 to postgres;
CREATE
DATABASE m1
  WITH OWNER = m1
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE m2 LOGIN
  PASSWORD 'm2'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant m2 to postgres;
CREATE
DATABASE m2
  WITH OWNER = m2
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE m3 LOGIN
  PASSWORD 'm3'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant m3 to postgres;
CREATE
DATABASE m3
  WITH OWNER = m3
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE coinbase LOGIN
  PASSWORD 'coinbase'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant coinbase to postgres;
CREATE
DATABASE coinbase
  WITH OWNER = coinbase
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;
