CREATE ROLE miner1 LOGIN
  PASSWORD 'miner1'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE miner2 LOGIN
  PASSWORD 'miner2'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE miner3 LOGIN
  PASSWORD 'miner3'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;


grant miner1 to postgres;
grant miner2 to postgres;
grant miner3 to postgres;


CREATE
DATABASE ubsv1
  WITH OWNER = miner1
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;
CREATE
DATABASE ubsv2
  WITH OWNER = miner2
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;
CREATE
DATABASE ubsv3
  WITH OWNER = miner3
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE coinbase LOGIN
  PASSWORD 'coinbase'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant coinbase to postgres;
CREATE
DATABASE coinbase
  WITH OWNER = coinbase
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;
