CREATE ROLE miner1 LOGIN
  PASSWORD 'miner1'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant miner1 to postgres;
CREATE
DATABASE ubsv1
  WITH OWNER = miner1
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE miner2 LOGIN
  PASSWORD 'miner2'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant miner2 to postgres;
CREATE
DATABASE ubsv2
  WITH OWNER = miner2
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE miner3 LOGIN
  PASSWORD 'miner3'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant miner3 to postgres;
CREATE
DATABASE ubsv3
  WITH OWNER = miner3
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE m1 LOGIN
  PASSWORD 'm1'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant m1 to postgres;
CREATE
DATABASE m1
  WITH OWNER = m1
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE m2 LOGIN
  PASSWORD 'm2'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant m2 to postgres;
CREATE
DATABASE m2
  WITH OWNER = m2
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE m3 LOGIN
  PASSWORD 'm3'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant m3 to postgres;
CREATE
DATABASE m3
  WITH OWNER = m3
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE m4 LOGIN
  PASSWORD 'm4'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant m4 to postgres;
CREATE
DATABASE m4
  WITH OWNER = m4
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE m5 LOGIN
  PASSWORD 'm5'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant m5 to postgres;
CREATE
DATABASE m5
  WITH OWNER = m5
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE m6 LOGIN
  PASSWORD 'm6'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant m6 to postgres;
CREATE
DATABASE m6
  WITH OWNER = m6
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE coinbase LOGIN
  PASSWORD 'coinbase'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant coinbase to postgres;
CREATE
DATABASE coinbase
  WITH OWNER = coinbase
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE coinbase_allinone LOGIN
  PASSWORD 'coinbase_allinone'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant coinbase_allinone to postgres;
CREATE
DATABASE coinbase_allinone
  WITH OWNER = coinbase_allinone
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE coinbase1 LOGIN
  PASSWORD 'coinbase1'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant coinbase1 to postgres;
CREATE
DATABASE coinbase1
  WITH OWNER = coinbase1
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE coinbase2 LOGIN
  PASSWORD 'coinbase2'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant coinbase2 to postgres;
CREATE
DATABASE coinbase2
  WITH OWNER = coinbase2
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE coinbase3 LOGIN
  PASSWORD 'coinbase3'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant coinbase3 to postgres;
CREATE
DATABASE coinbase3
  WITH OWNER = coinbase3
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE coinbase4 LOGIN
  PASSWORD 'coinbase4'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant coinbase4 to postgres;
CREATE
DATABASE coinbase4
  WITH OWNER = coinbase4
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE coinbase5 LOGIN
  PASSWORD 'coinbase5'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant coinbase5 to postgres;
CREATE
DATABASE coinbase5
  WITH OWNER = coinbase5
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;

CREATE ROLE coinbase6 LOGIN
  PASSWORD 'coinbase6'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
grant coinbase6 to postgres;
CREATE
DATABASE coinbase6
  WITH OWNER = coinbase6
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;
